#!/usr/bin/env python3
"""Regenerate the query index pages from YAML frontmatter in sources/ and wiki/.

Emits six deterministic cross-reference indices under queries/:
    by-problem.md          pattern pages -> symptom -> candidate techniques
    by-technique.md        technique pages with arch/confidence/reproducibility
    by-hardware-feature.md  hardware feature -> related pages
    by-repo.md             source-pr pages grouped by repository
    by-kernel-type.md      kernel type -> pages
    by-language.md         language guide + consumer pages

The output is deterministic: pages are collected in sorted path order and every
grouping is emitted in sorted key order, so regenerating twice with no content
change produces no diff. On an empty knowledge base every index is still
written as a valid, header-only document.

Design lineage: the six-index layout and the "auto-generated, do not edit"
contract follow the reference knowledge base; this generator is original code
and uses the pre-Hopper controlled vocabulary.

Usage:
    generate-indices.py            # regenerate into <root>/queries/
    generate-indices.py --root DIR
"""

from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _wiki_root import WIKI_ROOT as _DEFAULT_ROOT  # noqa: E402

AUTOGEN_NOTE = "> Auto-generated by scripts/generate-indices.py. Do not edit manually."


def extract_frontmatter(filepath: Path):
    content = filepath.read_text(encoding="utf-8")
    m = re.match(r"^---\s*\r?\n(.*?)\r?\n---\s*\r?\n?", content, re.DOTALL)
    if not m:
        return None
    try:
        return yaml.safe_load(m.group(1))
    except yaml.YAMLError:
        return None


def qlink(path: str) -> str:
    """Link relative from the queries/ directory back into the repo."""
    return f"../{path}"


def collect_all_pages(root: Path):
    pages = []
    errors = []
    for subdir in ("sources", "wiki"):
        base = root / subdir
        if not base.exists():
            continue
        for md in sorted(base.rglob("*.md")):
            rel = md.relative_to(root).as_posix()
            fm = extract_frontmatter(md)
            if fm is None:
                errors.append(f"{rel}: missing or unparseable frontmatter")
            elif not isinstance(fm, dict):
                errors.append(f"{rel}: frontmatter is {type(fm).__name__}, not a mapping")
            else:
                fm["_path"] = rel
                pages.append(fm)
    if errors:
        print(f"ERROR: {len(errors)} file(s) have missing/unparseable frontmatter:")
        for e in errors:
            print(f"  {e}")
        print("Run `uv run python scripts/validate.py` first to fix these files.")
        sys.exit(1)
    return pages


def load_vocab_set(root: Path, key: str) -> set:
    tags_path = root / "data" / "tags.yaml"
    if tags_path.exists():
        data = yaml.safe_load(tags_path.read_text(encoding="utf-8")) or {}
        return set(data.get(key, []) or [])
    return set()


def _header(title: str) -> list[str]:
    return [f"# Query: {title}", "", AUTOGEN_NOTE, ""]


def generate_by_problem(pages, root):
    id_map = {p["id"]: p for p in pages if "id" in p}
    lines = _header("By Problem / Symptom")
    lines += [
        "| Symptom | Pattern Page | Candidate Techniques | Sources |",
        "|---------|--------------|----------------------|---------|",
    ]
    for p in sorted((p for p in pages if p.get("type") == "pattern"),
                    key=lambda x: x.get("title", "")):
        symptoms = ", ".join(p.get("symptoms", []) or [])
        title = p.get("title", "Untitled")
        path = qlink(p["_path"])
        tech_links = []
        for tid in p.get("candidate_techniques", []) or []:
            if tid in id_map:
                t = id_map[tid]
                tech_links.append(f"[{t.get('title', tid)}]({qlink(t['_path'])})")
            else:
                tech_links.append(tid)
        techniques = ", ".join(tech_links)
        src_count = len(p.get("sources", []) or [])
        lines.append(f"| {symptoms} | [{title}]({path}) | {techniques} | {src_count} sources |")
    return "\n".join(lines) + "\n"


def generate_by_technique(pages, root):
    lines = _header("By Technique")
    lines += [
        "| Technique | Tags | Architectures | Confidence | Reproducibility | Sources |",
        "|-----------|------|---------------|------------|-----------------|---------|",
    ]
    for t in sorted((p for p in pages if p.get("type") == "technique"),
                    key=lambda x: x.get("title", "")):
        title = t.get("title", "Untitled")
        path = qlink(t["_path"])
        tags = ", ".join((t.get("tags", []) or [])[:4])
        archs = ", ".join(t.get("architectures", []) or [])
        conf = t.get("confidence", "")
        repro = t.get("reproducibility", "")
        src_count = len(t.get("sources", []) or [])
        lines.append(f"| [{title}]({path}) | {tags} | {archs} | {conf} | {repro} | {src_count} |")
    return "\n".join(lines) + "\n"


def generate_by_hardware_feature(pages, root):
    lines = _header("By Hardware Feature")
    hw_tag_set = load_vocab_set(root, "hardware_features")
    feature_pages = defaultdict(list)
    for p in pages:
        indexed = set()
        for feat in p.get("hardware_features", []) or []:
            feature_pages[feat].append(p)
            indexed.add(feat)
        for tag in p.get("tags", []) or []:
            if tag in hw_tag_set and tag not in indexed:
                feature_pages[tag].append(p)
                indexed.add(tag)
    lines += ["| Feature | Related Pages |", "|---------|---------------|"]
    for feat in sorted(feature_pages.keys()):
        page_links = []
        seen = set()
        for p in feature_pages[feat]:
            pid = p.get("id", p.get("_path", ""))
            if pid not in seen:
                seen.add(pid)
                page_links.append(f"[{p.get('title', pid)}]({qlink(p['_path'])})")
        lines.append(f"| `{feat}` | {', '.join(page_links)} |")
    return "\n".join(lines) + "\n"


def generate_by_repo(pages, root):
    lines = _header("By Repository")
    repos = defaultdict(list)
    for p in pages:
        if "repo" in p and "pr" in p:
            repos[p["repo"]].append(p)
    if not repos:
        lines.append("_No source-PR pages yet._")
        return "\n".join(lines) + "\n"
    for repo in sorted(repos.keys()):
        prs = sorted(repos[repo], key=lambda x: str(x.get("date", "")), reverse=True)
        slug = repo.lower().replace("/", "")
        lines.append(f'<a id="{slug}"></a>')
        lines.append(f"## {repo}")
        lines.append(f"{len(prs)} PRs")
        lines.append("")
        lines.append("| PR | Title | Date | Tags |")
        lines.append("|----|-------|------|------|")
        for pr in prs:
            pr_num = pr.get("pr", "?")
            title = pr.get("title", "Untitled")
            date = pr.get("date", "")
            path = qlink(pr["_path"])
            tags = ", ".join(list(dict.fromkeys(pr.get("tags", []) or []))[:3])
            lines.append(f"| [#{pr_num}]({path}) | {title} | {date} | {tags} |")
        lines.append("")
    return "\n".join(lines) + "\n"


def generate_by_kernel_type(pages, root):
    lines = _header("By Kernel Type")
    lines += ["| Kernel Type | Pages |", "|-------------|-------|"]
    kt_tag_set = load_vocab_set(root, "kernel_types")
    kernel_bearing_types = {"kernel", None}
    type_pages = defaultdict(list)
    for p in pages:
        explicit = p.get("kernel_types", []) or []
        if explicit:
            for kt in explicit:
                type_pages[kt].append(p)
        elif p.get("type") in kernel_bearing_types:
            for tag in p.get("tags", []) or []:
                if tag in kt_tag_set:
                    type_pages[tag].append(p)
    for kt in sorted(type_pages.keys()):
        page_links = []
        seen = set()
        for p in type_pages[kt]:
            pid = p.get("id", p.get("_path", ""))
            if pid not in seen:
                seen.add(pid)
                page_links.append(f"[{p.get('title', pid)}]({qlink(p['_path'])})")
        lines.append(f"| `{kt}` | {', '.join(page_links)} |")
    return "\n".join(lines) + "\n"


def generate_by_language(pages, root):
    lines = _header("By Language / DSL")
    valid_langs = load_vocab_set(root, "languages")
    lang_data = {lang: {"guide": None, "consumers": []} for lang in sorted(valid_langs)}

    for p in pages:
        if p.get("type") == "language":
            primary_lang = None
            for tag in p.get("tags", []) or []:
                if tag in valid_langs:
                    primary_lang = tag
                    break
            if not primary_lang:
                lang_id = p.get("id", "")
                if lang_id.startswith("lang-") and lang_id[5:] in valid_langs:
                    primary_lang = lang_id[5:]
            if primary_lang and primary_lang in lang_data:
                lang_data[primary_lang]["guide"] = p

    for p in pages:
        if p.get("type") == "language":
            continue
        explicit = p.get("languages", []) or []
        if explicit:
            for lang in explicit:
                if lang in lang_data:
                    lang_data[lang]["consumers"].append(p)
        else:
            for tag in p.get("tags", []) or []:
                if tag in lang_data:
                    lang_data[tag]["consumers"].append(p)

    lines += ["| Language | Guide | Related Pages |", "|----------|-------|---------------|"]
    for lang in sorted(lang_data.keys()):
        data = lang_data[lang]
        if not data["guide"] and not data["consumers"]:
            continue
        guide_link = ""
        if data["guide"]:
            g = data["guide"]
            guide_link = f"[{g.get('title', lang)}]({qlink(g['_path'])})"
        related = []
        seen = set()
        for p in data["consumers"]:
            pid = p.get("id", p.get("_path", ""))
            if pid not in seen:
                seen.add(pid)
                related.append(f"[{p.get('title', pid)}]({qlink(p['_path'])})")
        lines.append(f"| `{lang}` | {guide_link} | {', '.join(related)} |")
    return "\n".join(lines) + "\n"


GENERATORS = {
    "by-problem.md": generate_by_problem,
    "by-technique.md": generate_by_technique,
    "by-hardware-feature.md": generate_by_hardware_feature,
    "by-repo.md": generate_by_repo,
    "by-kernel-type.md": generate_by_kernel_type,
    "by-language.md": generate_by_language,
}


def main():
    parser = argparse.ArgumentParser(description="Regenerate pre-Hopper wiki query indices")
    parser.add_argument("--root", help="Knowledge-base root (default: autodetect)")
    args = parser.parse_args()
    root = Path(args.root).expanduser().resolve() if args.root else _DEFAULT_ROOT

    queries_dir = root / "queries"
    queries_dir.mkdir(exist_ok=True)
    pages = collect_all_pages(root)
    print(f"Collected {len(pages)} page(s) from sources/ and wiki/")
    for filename, gen in GENERATORS.items():
        content = gen(pages, root)
        (queries_dir / filename).write_text(content, encoding="utf-8")
        print(f"  Generated queries/{filename}")
    print("Done.")


if __name__ == "__main__":
    main()
